export const ERROR_CODES = {
  DUPLICATE: "DUPLICATE",
  DUPLICATE_EMAIL: "DUPLICATE_EMAIL",
  DUPLICATE_USERNAME: "DUPLICATE_USERNAME",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  NOT_FOUND: "NOT_FOUND",

  INVALID_PASSWORD: "INVALID_PASSWORD",

  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",

  BAD_REQUEST: "BAD_REQUEST",
  CONFLICT: "CONFLICT",
  UNPROCESSABLE_ENTITY: "UNPROCESSABLE_ENTITY",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

  VALIDATION_ERROR: "VALIDATION_ERROR",

  INVALID_EMAIL: "INVALID_EMAIL",
  PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
  USERNAME_TOO_SHORT: "USERNAME_TOO_SHORT",
  PASSWORD_CONFIRMATION_MISMATCH: "PASSWORD_CONFIRMATION_MISMATCH",

  UNKNOWN_ERROR: "UNKNOWN_ERROR",
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
